# .codacy.yml - Configuración optimizada para Hefest
version: 2

# Archivos a excluir del análisis
exclude_paths:
  - "data/*.db"
  - "data/*.db-*"
  - "logs/**"
  - "logs_debug/**"
  - "htmlcov/**"
  - "**/__pycache__/**"
  - "version-backups/**"
  - "**/*.pyc"
  - "docs/archive/**"
  - "Hefest_Backups/**"

# Herramientas habilitadas
engines:
  # Python - Análisis principal
  pylintpython3:
    enabled: true
    configuration_file: .pylintrc

  bandit:
    enabled: true
    configuration_file: bandit.yml

  prospector:
    enabled: true
    configuration_file: .prospector.yml

  ruff:
    enabled: true
    configuration_file: pyproject.toml

  # Seguridad
  trivy:
    enabled: true

  semgrep:
    enabled: true

  # Archivos de configuración
  jacksonlinter:
    enabled: true

  # Documentación
  markdownlint:
    enabled: true
    configuration_file: .markdownlint.json

  # Complejidad y métricas
  lizard:
    enabled: true

# Configuración de cobertura
coverage:
  enabled: true

# Configuración de duplicación
duplication:
  enabled: true
  languages:
    - python
  mass_threshold: 60

# Métricas
metrics:
  enabled: true
  languages:
    - python
