# GitHub Actions para automatizar releases
name: Release Hefest

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[build]
          
      - name: Build executable
        run: |
          python scripts/build_exe.py --clean --onefile --windowed
          
      - name: Upload Windows executable
        uses: actions/upload-artifact@v3
        with:
          name: hefest-windows
          path: dist/HEFEST.exe

  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build twine
          
      - name: Build package
        run: python -m build
        
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
